version: '3.3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  
  agendamento:
    depends_on:
      - mongodb
    image: juliocesar757/agendamento
    ports:
      - "8080:8080"
    restart: always

